name: Dart tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
      
      - name: Decode base64 secrets
        run: echo $SECRETS_FILE_CONFIGURATIONS | base64 --decode > lib/constants/hiden_configuration.dart
        env:
          SECRETS_FILE_CONFIGURATIONS: ${{ secrets.SECRETS_FILE_CONFIGURATIONS }}
          
      - name: Install dependencies
        run: dart pub get
        
      - name: Analyze project source
        run: dart analyze
        
      - name: Run tests
        run: dart test
